name: Deps
description: Install deps for a mix project
inputs:
  working-directory:
    description: "The path to the mix project's directory"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: ${{ format('{0}/{1}', inputs.working-directory, 'deps') }}
        key: ${{ inputs.working-directory }}-deps-${{ runner.os }}-${{ hashFiles(format('{0}/{1}', inputs.working-directory, 'mix.lock')) }}
        restore-keys: ${{ inputs.working-directory }}-deps-${{ runner.os }}-
    - run: mix deps.get
      if: steps.restore-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/cache/save@v3
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        path: deps
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
