name: Checks
on: [workflow_call]
jobs:
  core-checks:
    uses: ./.github/workflows/check.yaml
    with:
      working-directory: ./core
  live_query-checks:
    uses: ./.github/workflows/check.yaml
    with:
      working-directory: ./live_query
