name: CI
on: [push]
jobs:
  core_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/core_checks
  live_query-checks:
    uses: ./.github/workflows/live_query-checks.yaml
  core-prepare-to-publish:
    uses: ./.github/workflows/core-prepare-to-publish.yaml
  live_query-prepare-to-publish:
    uses: ./.github/workflows/live_query-prepare-to-publish.yaml
