name: Core Publish
on: [workflow_dispatch]
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
  core-prepare-to-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: ./.github/actions/deps
        with:
          working-directory: ./core
      - uses: ./.github/actions/compile
        with:
          working-directory: ./core
          mix-env: prod
  core-publish:
    needs: core-prepare-to-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "now publish..."
        shell: bash
