name: LiveQuery.Core Prepare to Publish
on: [workflow_call]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: ./.github/actions/deps
        with:
          working-directory: ./core
      - uses: ./.github/actions/compile
        with:
          working-directory: ./core
          mix-env: prod
