name: LiveQuery.Core Publish
on: [workflow_dispatch]
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
  core-prepare-to-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: ./.github/actions/deps
        with:
          working-directory: ./core
      - uses: ./.github/actions/compile
        with:
          working-directory: ./core
          mix-env: prod
  core-publish:
    needs:
      - checks
      - core-prepare-to-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        shell: bash
        working-directory: ./core
