name: LiveQuery.Core Publish
on:
  workflow_dispatch:
  push:
    tags:
      - publish-core
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
  core-prepare-to-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: ./.github/actions/deps
        with:
          working-directory: ./core
      - uses: ./.github/actions/compile
        with:
          working-directory: ./core
          mix-env: prod
  core-publish:
    needs:
      - checks
      - core-prepare-to-publish
    uses: ./.github/workflows/publish.yaml
    with:
      working-directory: ./core
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
