name: LiveQuery Publish
on:
  workflow_dispatch
  push:
    branches:
      - main
    tags:
      - publish-live_query
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
  live_query-prepare-to-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: ./.github/actions/deps
        with:
          working-directory: ./live_query
      - uses: ./.github/actions/compile
        with:
          working-directory: ./live_query
          mix-env: prod
  live_query-publish:
    needs:
      - checks
      - live_query-prepare-to-publish
    uses: ./.github/workflows/publish.yaml
    with:
      working-directory: ./live_query
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
