name: LiveQuery.Core Publish
on: [workflow_dispatch]
jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
  live_query-prepare-to-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: ./.github/actions/deps
        with:
          working-directory: ./live_query
      - uses: ./.github/actions/compile
        with:
          working-directory: ./live_query
          mix-env: prod
  live_query-publish:
    needs:
      - checks
      - live_query-prepare-to-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: HEX_API_KEY=${{ secrets.hex_api_key }} mix hex.publish --yes
        shell: bash
        working-directory: ./core
