name: LiveQuery.Core Checks
description: Run checks for LiveQuery.Core
runs:
  using: "composite"
  steps:
    - uses: team-alembic/staple-actions/actions/install-elixir@main
    - uses: ./.github/actions/deps
      with:
        working-directory: ./core
    - uses: ./.github/actions/compile
      with:
        working-directory: ./core
        mix-env: test
    - uses: ./.github/actions/test
      with:
        working-directory: ./core
